server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/admin-feng-9527/microservicecloud-config.git #github上仓库名字


